### ISSUE TITLE
Make tap-to-exit toggleable

### ISSUE THREAD

**Issue by wildabeast** [phonegap/phonegap-plugin-developer-mode#3]
Rather than just always enabling it.

Possibly a localStorage setting, settable from the parent developer app, and readable on the "child" apps.

Would a localStorage setting persist from dev app to child apps?

**Comment by purplecabbage** [comment]
postMessage might make more sense
localStorage is probably the easiest, but can be flakey

**Comment by timkim** [comment]
I think postMessage would be good but I don't think it'll quite work for the child app. If the user starts navigating around in their app, can you keep listening on the initial postMessage?

**Comment by timkim** [comment]
Added in this commit: https://github.com/phonegap/phonegap-plugin-developer-mode/commit/c0cf0b4b4f09ccbb3948b715eeb64a725db8b157
